### PR TITLE
jm-login

### PR DESCRIPTION
**Pull request by jkmccray**
did lotsa stuff

### CODE REVIEW

**Comment by Ellie-Ash** [comment]
WOW THIS LOOKS GREAT JKMCCRAY REALLY GOOD WORK HERE HOPE TO HEAR FROM YOU SOON TAKE CARE.

**Comment by spuuun** [comment]
Wow. whoa. wee. WHAM. say whaaaa?
merge it

**Comment by jkmccray** [comment]
AUNT MARY DIED. LOL MOM

**Comment by mstiles01** [comment]
Good ish

**Pull request merged**
